### PR TITLE
A first set of MatLab scripts

### PR DESCRIPTION
**Pull request by amereghe**
These are the MatLab scripts/functions that I have collected so far.

### CODE REVIEW

**Comment by amereghe** [comment]
This is not the whole batch of material, but at least a good starting point.
Functions are not in their super-final state, though they can be used with no issues.
There is already some docstrings explaining a bit what's behind...

**Comment by simonesavazzi** [comment]
Ciao ale, io sono ancora in ferie fino a dopodomani.
Giovedì sarò in cnao e se ci sei guardiamo insieme

Buona serata

Simone
________________________________________
Da: Alessio Mereghetti [notifications@github.com]
Inviato: lunedì 4 gennaio 2021 17:01
A: CNAO/MatLabTools
Cc: Savazzi Simone; Review requested
Oggetto: Re: [CNAO/MatLabTools] A first set of MatLab scripts (#1)

This is not the whole batch of material, but at least a good starting point.
Functions are not in their super-final state, though they can be used with no issues.
There is already some docstrings explaining a bit what's behind...

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://eu-central-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL0NOQU8vTWF0TGFiVG9vbHMvcHVsbC8xI2lzc3VlY29tbWVudC03NTQwNTk3MTU=&i=NWVlYzdjMzI2NTY5NzEwZTA0ZDQ1ODM0&t=ZkdBZWhYalBtNFcxTzNoczFPckpaZGxKRW1JMTJZeG5LcjFuTHhlQXRWTT0=&h=7772c0c99cb64158aca75194ffb819fe>, or unsubscribe<https://eu-central-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BU0ZRSk5LNloyTE1JSkFUNTc2WU0yVFNZSFE0SkFOQ05GU000VTdQVlFWUQ==&i=NWVlYzdjMzI2NTY5NzEwZTA0ZDQ1ODM0&t=SVhFVlBldU5WUEg2cWNKeDIrYkp2TnByR1g3WG92SlZydzZzcEMxNXExZz0=&h=7772c0c99cb64158aca75194ffb819fe>.

________________________________
[Dona il tuo 5x1000 alla Fondazione CNAO]
________________________________
Questo messaggio di posta elettronica ed i suoi allegati contengono informazioni di carattere confidenziale rivolte esclusivamente al destinatario.E' vietato l'uso, la diffusione,
la distribuzione o la riproduzione da parte di ogni altra persona. Nel caso aveste ricevuto questo messaggio per errore, siete pregati di segnalarlo immediatamente al mittente e
di distruggerlo (compresi i file allegati) senza farne copia.
Mail confidentialy footer.
This e-mail and any attachment are confidential and may be privileged or otherwise protected from disclosure. It is solely intended for the person(s) named above.
If you are not the intended recipient, any reading, use, disclosure, copying or distribution of all or parts of this e-mail or associated attachments is strictly prohibited.
________________________________

**Comment by amereghe** [comment]
Figurati, Simone, non c'è fretta, goditi pure le vacanze! Possiamo vedere la PR tranquillamente giovedì.
A presto,

**Comment by amereghe** [comment]
something went wrong with my fork, and did not manage to get back to work.
Starting over from scratch with PR #2

**Pull request closed without merging**
