### PR TITLE
added examples of startup and pathdef files

### PR DESCRIPTION
**Pull request by enricofelcini**
MatLab automatically runs the file named "startup.m" if it is saved in a known folder in the path (for example C:/Users/**name.surname**/Documents/MATLAB).

The pathdef.m file is an example for the format: _all the path name need to be changed for each user_

### CODE REVIEW

**Comment by amereghe** [comment]
Hi @enricofelcini ,
many thanks for the PR. Maybe you could write in the `README.md` file a couple of lines, showing how to use the two new files.
I will then merge the PR with great pleasure!
In the meanwhile, I will merge PR #8 - so you will need to update your PR, but you will do that anyway :)
Cheers,
A.

**Comment by enricofelcini** [comment]
> Hi @enricofelcini ,
> many thanks for the PR. Maybe you could write in the `README.md` file a couple of lines, showing how to use the two new files.
> I will then merge the PR with great pleasure!
> In the meanwhile, I will merge PR #8 - so you will need to update your PR, but you will do that anyway :)
> Cheers,
> A.

I have now added a brief explanation in the readme.md file

**Comment by amereghe** [comment]
Hi @enricofelcini ,
thanks! ...but the diff does not show the changes on the README.md file. Have you pushed them?
Cheers,
A.

**Comment by enricofelcini** [comment]
Bizarre…I can see the commit in the CNAO repo
https://github.com/CNAO/MatLabTools/commit/7c9547e2fcbc7b9388397047f130adab59740674
Am I wrong?

Da: Alessio Mereghetti ***@***.***
Inviato: mercoledì 28 aprile 2021 14:55
A: CNAO/MatLabTools
Cc: Felcini Enrico; Mention
Oggetto: Re: [CNAO/MatLabTools] added examples of startup and pathdef files (#9)


Hi @enricofelcini<https://eu-central-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL2Vucmljb2ZlbGNpbmk=&i=NWY3NDU3MjAyNmIwMjQwZTExYTg0YzI5&t=Vml5T0dqSGdDYk1YMW9sNFZhMmlVeStvUHlMNWM0b0dOdEJndEFjV1ZwOD0=&h=b8baba7b36524a0787df25539f958ef6> ,
thanks! ...but the diff does not show the changes on the README.md file. Have you pushed them?
Cheers,
A.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eu-central-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL0NOQU8vTWF0TGFiVG9vbHMvcHVsbC85I2lzc3VlY29tbWVudC04Mjg0MzExMzc=&i=NWY3NDU3MjAyNmIwMjQwZTExYTg0YzI5&t=RWNUUmRkT3g4bTlqd2puOWpNeDU3SzUrb2FINmkwcFZkaGpBZ0FqM1NTYz0=&h=b8baba7b36524a0787df25539f958ef6>, or unsubscribe<https://eu-central-1.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BU0ZCTzJYTzZLTEVUQlRWM1RGQk1ETFRMQUFRTkFOQ05GU000MjdDU1ZVUQ==&i=NWY3NDU3MjAyNmIwMjQwZTExYTg0YzI5&t=Nm1qRVdnQmVabVFoSzN1dWlFWm9pMHFuTVlDRjZnSUJ2bWVvbkpoVVFZVT0=&h=b8baba7b36524a0787df25539f958ef6>.

________________________________
[Dona il tuo 5x1000 alla Fondazione CNAO]
________________________________
Questo messaggio di posta elettronica ed i suoi allegati contengono informazioni di carattere confidenziale rivolte esclusivamente al destinatario.E' vietato l'uso, la diffusione,
la distribuzione o la riproduzione da parte di ogni altra persona. Nel caso aveste ricevuto questo messaggio per errore, siete pregati di segnalarlo immediatamente al mittente e
di distruggerlo (compresi i file allegati) senza farne copia.
Mail confidentialy footer.
This e-mail and any attachment are confidential and may be privileged or otherwise protected from disclosure. It is solely intended for the person(s) named above.
If you are not the intended recipient, any reading, use, disclosure, copying or distribution of all or parts of this e-mail or associated attachments is strictly prohibited.
________________________________

**Comment by amereghe** [comment]
ok sorry, because you directly edited the README in the main of the project repo, not in your branch upon which the PR is based.
No worries, I merge

**Pull request merged**
